In [2]:
import numpy as np

a = np.random.randint(1, 10, size=(3,4,2))

print(a)

[[[5 6]
  [5 3]
  [3 1]
  [7 3]]

 [[3 6]
  [6 1]
  [5 4]
  [4 2]]

 [[6 6]
  [1 6]
  [7 8]
  [1 7]]]


In [3]:
a=np.array([6,7,8,9,10])
a[2]

np.int64(8)

In [4]:
a[[2,3]]

array([8, 9])

In [ ]:
,[5,7,8,9,11]]])

In [6]:
a[0]

array([ 6,  7,  8,  9, 10])

In [10]:
a[0,0,1]

np.int64(7)

In [11]:
a=np.array([6,7,8,9,10])
a[0:3]

array([6, 7, 8])

In [12]:
a[[0,1,2]]

array([6, 7, 8])

In [13]:
a[[1,2,0]]

array([7, 8, 6])

In [14]:
a>8

array([False, False, False,  True,  True])

In [15]:
a

array([ 6,  7,  8,  9, 10])

In [17]:
a[[True,True,True,False,True]]

array([ 6,  7,  8, 10])

In [18]:
a[a>8]

array([ 9, 10])

In [19]:
import numpy as np

a = np.array([1,2,3,4,5])

np.save("myarray.npy", a)

In [20]:
b = np.load("myarray.npy")

print(b)

[1 2 3 4 5]


In [22]:
import json 
# Create dictionary
data = {
    "name": "Malavika",
    "age": 20,
    "course": "Mathematics"
}


In [23]:
with open("demo.json","w") as j:
    json.dump(data,j)

In [24]:
with open("demo.json","r") as j:
    a=json.load(j)

In [25]:
a

{'name': 'Malavika', 'age': 20, 'course': 'Mathematics'}

In [26]:
import pickle

In [27]:
data=100

In [28]:
with open("demo.pkl","wb") as j:
    pickle.dump(data,j)

In [30]:
with open("demo.pkl","rb") as j:
    a=pickle.load(j)

In [31]:
a

100

In [32]:
a=np.array([5,6,7,8])

In [33]:
a.max()

np.int64(8)